# 階段形式

*階段形式* とは三角行列の一般化。

$  \left[ \begin{array}{rrr} 0 & 2 & 3 & 0 & 5 & 6 \\ 0 & 0 & 1 & 0 & 3 & 4 \\ 0 & 0 & 0 & 0 & 1 & 2 \\ 0 & 0 & 0 & 0 & 0 & 9 \end{array} \right] $

行列 $ A $ の各行に対し、0でない要素が初めて現れる列の様子が右下がりの階段のようになっている。

## 階段形式からベクトル空間の基底へ

### 行列が階段形式ならば、0でない要素を持つ行は行ベクトルの基底を成す。
例えば、

$  \left[ \begin{array}{rrr} 0 & 2 & 3 & 0 & 5 & 6 \\ 0 & 0 & 1 & 0 & 3 & 4 \\ 0 & 0 & 0 & 0 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 & 0 \end{array} \right] $

の行ベクトルの基底は、
$  \left[ \begin{array}{rrr} 0 & 2 & 3 & 0 & 5 & 6  \end{array} \right] $
$  \left[ \begin{array}{rrr} 0 & 0 & 1 & 0 & 3 & 4  \end{array} \right] $
である。

## 行を０でない要素がはじめて現れる位置でソートする。


 

In [1]:
import numpy as np


In [2]:
def calc_rowlist(a):
    r = []
    for row in a:
        pos = row.nonzero()[0][0]
        r.append(pos)
    return r

In [3]:
def conv_echelon_form(a):
    row_list = calc_rowlist(a)
    b = []
    for c in range(len(row_list)):
        try:
            idx = row_list.index(c)
            pivot = a[idx]
            b.append(pivot)
        except ValueError:
            continue

    return np.array(b, dtype=np.float32)

In [4]:
alist = [[0, 2, 3, 4, 5],
         [0, 0, 0, 3, 2],
         [1, 2, 3, 4, 5],
         [0, 0, 0, 6, 7],
         [0, 0, 0, 9, 8]]


In [5]:
A = np.array(alist, dtype=np.float32)
B = conv_echelon_form(A)

print(A)
print(B)

[[ 0.  2.  3.  4.  5.]
 [ 0.  0.  0.  3.  2.]
 [ 1.  2.  3.  4.  5.]
 [ 0.  0.  0.  6.  7.]
 [ 0.  0.  0.  9.  8.]]
[[ 1.  2.  3.  4.  5.]
 [ 0.  2.  3.  4.  5.]
 [ 0.  0.  0.  3.  2.]]


新しく追加する行をピボットと言う。
階段になっていないというのもあるが、行が減っているので上手く動いていない。



## 行基本変形
ピボット行を適切に定数倍したものを、他の残った行から引いて、要素を０にする。

In [8]:
def calc_rowlist(a):
    r = []
    for row in a:
        try:
            pos = row.nonzero()[0][0]
            r.append(pos)
        except IndexError:
            r.append(-1)
    return r

In [6]:
def conv_echelon_form(a):
    row_list = calc_rowlist(a)
    b = []
    for c in range(len(row_list)):
        first = True
        first_pivot = []
        for v, i in zip(row_list, range(len(row_list))):
            if c == v:
                pivot = a[i]
                if first:
                    # 要素が全て０じゃなければ追加
                    if len(np.where(pivot != 0)[0]) != 0:
                        first_pivot = pivot
                        first = False
                        b.append(pivot)
                else:
                    # ピボット行以外の処理
                    mult = a[i][c] / first_pivot[c]
                    a[i] -= mult * first_pivot
                    row_list = calc_rowlist(a)

    return np.array(b, dtype=np.float32)

In [10]:
alist = [[0, 2, 3, 4, 5],
         [0, 0, 0, 3, 2],
         [1, 2, 3, 4, 5],
         [0, 0, 0, 6, 7],
         [0, 0, 0, 9, 8]]

A = np.array(alist, dtype=np.float32)
B = conv_echelon_form(A)

print(B)

[[ 1.  2.  3.  4.  5.]
 [ 0.  2.  3.  4.  5.]
 [ 0.  0.  0.  3.  2.]
 [ 0.  0.  0.  0.  3.]]
