# tensor flow memo
再量子化の所が間違ってる.

In [27]:
import numpy as np

# 2bitの最大値
MAX_VALUE = 3 

def deQuantize(arr, max, min):
    """量子化を元に戻す"""
    gain = (max - min) / MAX_VALUE
    return arr * gain + min

# a = [0,1,2,3]
qt_a = np.array([0, 1, 2, 3])
max_a = 3
min_a = 0
print(deQuantize(qt_a,max_a,min_a))

# b = [4, 6, 8, 10]
qt_b = np.array([0, 1, 2, 3])
max_b = 10
min_b = 4
print(deQuantize(qt_b,max_b,min_b))

# c = a + b
# 倍率を求める
gain = (max_b - min_b) / (max_a - min_a)
qt_c = qt_b * gain + qt_a
# qt_cの最大値が9なので、2bitに収めるために３で割る。
# 新しい量子化
q_param = np.max(qt_c) / MAX_VALUE
qt_c /= q_param

# 最大値、最小値は足すだけ
min_c = min_a + min_b
max_c = max_a + max_b

# 一応これでも計算はできてる。
print(deQuantize(qt_c,max_c,min_c))

[ 0.  1.  2.  3.]
[  4.   6.   8.  10.]
[  4.   7.  10.  13.]


In [28]:
# 答え合わせ
a = np.array([0,1,2,3])
b = np.array([4,6,8,10])
print(a+b)

[ 4  7 10 13]


In [ ]:
OK